on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  code-quality:
    name: Code quality
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: cq
      rust_target: wasm32-unknown-unknown

  test:
    name: Run tests
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: test

  no-std:
    name: Run no-std checks
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: no-std

  build-benches:
    name: Build benchmarks
    uses: dusk-network/.github/.github/workflows/run-make.yml@main
    with:
      make_target: build-benches
