on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  rustfmt:
    name: Rust Format
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: cargo fmt --all -- --check

  test:
    name: Tests
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: make test

  no-std:
    name: no_std + WASM
    runs-on: core
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - run: make no-std
