on:
  pull_request:
  push:
    branches:
      - master

name: Continuous integration

jobs:
  code_analysis:
    name: Code Analysis
    uses: dusk-network/.github/.github/workflows/code-analysis.yml@main

  test_nightly:
    name: Nightly tests std
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main

  build_nightly_nostd:
      name: Nightly build no_std
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: Swatinem/rust-cache@v2
        # ARM contains no std lib. Just core and alloc.
        - run: rustup target add thumbv6m-none-eabi
        - run: cargo build --release --no-default-features --target thumbv6m-none-eabi

  test_nightly_canon_features:
    name: Nightly tests canon
    uses: dusk-network/.github/.github/workflows/run-tests.yml@main 
    with:
      test_flags: --no-default-features --features canon
